batch_size: 128
data_root: /home/magali/CV4Ecology-summer-school
device: cuda
image_size:
- 224
- 224
json_file_train: FinalDataset/SubsetAgeModelCocoTrain_croppedID.json
json_file_val: FinalDataset/SubsetAgeModelCocoVal_croppedID.json
learning_rate: 0.0001
num_classes: 2
num_epochs: 200
num_workers: 4
save_dir: /home/magali/ct_classifier/model_states_age/
seed: 32678456782
weight_decay: 0.001
