# Here's where you define experiment-specific hyperparameters.
# You can also create lists and group parameters together into nested sub-parts.
# In Python, this is all read as a dict.

# environment/computational parameters
seed: 19837552478        # run 1, random number generator seed (long integer value)
#seed: 19888762332         # run 2
#seed: 99871887355         # run 3
#seed: 12367498679         # run 4
#seed: 10922335098         # run 5
device: cuda
num_workers: 4

# dataset parameters
data_root: /home/magali/CV4Ecology-summer-school
num_classes: 2

json_file_train:  FinalDataset/SexModelRoeDeerMarchAugCocoTrain_croppedID.json
json_file_val: FinalDataset/SexModelRoeDeerMarchAugCocoVal_croppedID.json
json_file_test: FinalDataset/SexModelRoeDeerMarchAugCocoTest_croppedID.json
save_dir: /home/magali/ct_classifier/model_states_sexRoeDeer/

# training hyperparameters
image_size: [224, 224]
num_epochs: 100
batch_size: 128
learning_rate: 0.0001
weight_decay: 0.001

# overwrite .pt files?
overwrite: False